import re

with open("src/graph_builders/connectivity_builder.py", "r") as f:
    content = f.read()

# Docstring
content = content.replace("merge_edges_by_component_pair: Group edges", "merge_segments_by_component_pair: Group segments")

# merge_edges_by_component_pair
content = content.replace("def merge_edges_by_component_pair(raw_edges, nodes_dict=None):", "def merge_segments_by_component_pair(raw_traces, nodes_dict=None):")
content = content.replace("List of segment edges", "List of traces")
content = content.replace("List of merged edges", "List of merged segments")
content = content.replace("edge_groups = {}", "segment_groups = {}")
content = content.replace("for edge in raw_edges:", "for trace in raw_traces:")
content = content.replace("if edge['node_a']", "if trace['node_a']")
content = content.replace("edge['node_b']", "trace['node_b']")
content = content.replace("key = tuple(sorted([edge['node_a']", "key = tuple(sorted([trace['node_a']")
content = content.replace("edge_groups[key] = []", "segment_groups[key] = []")
content = content.replace("edge_groups[key].append(edge)", "segment_groups[key].append(trace)")
content = content.replace("merged_edges = []", "merged_segments = []")
content = content.replace("for (node_a, node_b), edges_in_group in edge_groups.items():", "for (node_a, node_b), traces_in_group in segment_groups.items():")
content = content.replace("for edge in edges_in_group:", "for trace in traces_in_group:")
content = content.replace("all_tapes.update(edge['tapes'])", "all_tapes.update(trace['tapes'])")
content = content.replace("if edge.get('source')", "if trace.get('source')")
content = content.replace("if edge.get('dimension_mm')", "if trace.get('dimension_mm')")
content = content.replace("edge['dimension_mm']", "trace['dimension_mm']")
content = content.replace("merged_edge =", "merged_segment =")
content = content.replace("'segment_count': len(edges_in_group)", "'trace_count': len(traces_in_group)")
content = content.replace("'segments': edges_in_group", "'traces': traces_in_group")
content = content.replace("edge.get('snapped_a", "trace.get('snapped_a")
content = content.replace("edge.get('snapped_b", "trace.get('snapped_b")
content = content.replace("merged_edges.append(merged_edge)", "merged_segments.append(merged_segment)")
content = content.replace("Raw edges: {len(raw_edges)}", "Raw traces: {len(raw_traces)}")
content = content.replace("Merged connections: {len(merged_edges)}", "Merged connections: {len(merged_segments)}")
content = content.replace("return merged_edges", "return merged_segments")
content = content.replace("Edge Merging", "Segment Merging")

# convert_to_legacy_format
content = content.replace("    edges = []", "    segments = []")
content = content.replace("edges.append({", "segments.append({")
content = content.replace("'segment_count': 1,", "'trace_count': 1,")
content = content.replace("'segments': [{", "'traces': [{")
content = content.replace("'edges': edges,", "'segments': segments,")
content = content.replace("'raw_edges': edges,", "'raw_traces': segments,")
content = content.replace("'segment_tapes': {},", "'trace_tapes': {},")

# build_connectivity_graph_heuristic
content = content.replace("'edges' (list of connections)", "'segments' (list of connections)")
content = content.replace("segment_tapes =", "trace_tapes =")
content = content.replace("for seg_idx, seg in enumerate(detected_wires):", "for trace_idx, trace in enumerate(detected_wires):")
content = content.replace("seg['p1']", "trace['p1']")
content = content.replace("seg['p2']", "trace['p2']")
content = content.replace("seg_vec =", "trace_vec =")
content = content.replace("seg_len =", "trace_len =")
content = content.replace("seg_len < 1:", "trace_len < 1:")
content = content.replace("seg_unit =", "trace_unit =")
content = content.replace("seg_vec / seg_len", "trace_vec / trace_len")
content = content.replace("tapes_on_segment", "tapes_on_trace")
content = content.replace("segment_tapes.get(seg_idx", "trace_tapes.get(trace_idx")
content = content.replace("segment_tapes[seg_idx]", "trace_tapes[trace_idx]")
content = content.replace("raw_edges = []", "raw_traces = []")
content = content.replace("raw_edges.append(segment_info)", "raw_traces.append(segment_info)")
content = content.replace("segment_info =", "trace_info =")
content = content.replace("segment_info[", "trace_info[")
content = content.replace("tape_pass_edges", "tape_pass_traces")
content = content.replace("tape_pass_traces =", "tape_pass_traces =")
content = content.replace("edges directly from tape", "traces directly from tape")
content = content.replace("tape_pass_traces.append", "tape_pass_traces.append")
content = content.replace("tape_pass_traces.extend", "tape_pass_traces.extend")
content = content.replace("all_raw_edges =", "all_raw_traces =")
content = content.replace("edges = merge_edges_by_component_pair(all_raw_edges,", "segments = merge_segments_by_component_pair(all_raw_traces,")
content = content.replace("'edges': edges,", "'segments': segments,")
content = content.replace("'raw_edges': all_raw_edges,", "'raw_traces': all_raw_traces,")
content = content.replace("'segment_tapes': segment_tapes", "'trace_tapes': trace_tapes")

with open("src/graph_builders/connectivity_builder.py", "w") as f:
    f.write(content)
